### ISSUE TITLE
Lambda function

### ISSUE THREAD

**Issue by etiennea** [esbenp/pdf-bot#3]
Could we have an example of a lambda function for this?

**Comment by JasonShin** [comment]
You can easily build an equivalent Lambda function on your own. It took me like 20 lines to code it last time.

**Comment by esbenp** [comment]
I am sorry I am not familiar with Lambda functions. If you write on feel free to submit it though so it can be included as an example :-)

**Comment by JasonShin** [comment]
Sure, I can try doing that over the weekend =)...

**Comment by esbenp** [comment]
Sounds good!

**Comment by mattcodez** [comment]
@JasonShin Did you look into this at all by chance? I'm curious what your thoughts are for implementing this on Lambda, would you just leave a Chrome instance running on an EC2 box? What all would the Lambda portion be responsible for?

**Comment by JasonShin** [comment]
Sorry, guys haha... totally forgot about this ... I wouldn't worry about "bot" aspect of this application at all because you would probably want to use Lambda as a stateless function as a service. I would probably just grab https://github.com/esbenp/pdf-bot/blob/master/src/pdfGenerator.js and turn it into a Lambda function (ideally use serverless framework)
